### ISSUE TITLE
Display paths of results

### ISSUE THREAD

**Issue by Monica2511** [HANyangguang/GCBIR#1]
Your project is pretty cool. I'm trying to create an cbir system and i want to get path/file-name of images results. I'm not gud in python so can you show me a way to get it. Tks verymuch!

**Comment by HANyangguang** [comment]
Hi, Monica, thanks for your interest in the GCBIR! Pls note that for each image in the image datasets, there is an individual image path in the `img_paths` list, ```img_paths = [img_path for img_path in sorted(glob.glob('static/dataset/*/*.[Jj][Pp][Gg]'))]```
where * means anything string.
We can use the index in the img_paths list to obtain each image path, see  ```scores = [(distance, img_paths[id]) for (distance, id) in zip(distances, ids)]```, this line of code shows that, after we get the distances, `ids` from the get_nns_by_vector method, we can facilitate the index in the `ids` to get the path of each of the image results by `img_paths[id]` and finally, I store it in the `scores` to pass to the HTML file to show the image.

**Comment by HANyangguang** [comment]
If you want to see the path/file-name of images results, you can print the `scores`, where scores[1] represents the img_path.

**Comment by Monica2511** [comment]
Thank you for such a detailed answer. Have a nice day!
